# Generated by Django 3.2.20 on 2024-05-13 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=120)),
                ('jabatan', models.CharField(max_length=120)),
                ('offset', models.BooleanField(default=False)),
                ('child', models.ManyToManyField(related_name='_organizational_structure_nodes_child_+', to='organizational_structure.Nodes')),
                ('child_offsets', models.ManyToManyField(related_name='_organizational_structure_nodes_child_offsets_+', to='organizational_structure.Nodes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=120)),
                ('nodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_structure.nodes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
