# Generated by Django 3.2.20 on 2024-05-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='child',
            field=models.ManyToManyField(related_name='child_list', to='organizational_structure.Nodes'),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='child_offsets',
            field=models.ManyToManyField(related_name='child_offsets_list', to='organizational_structure.Nodes'),
        ),
    ]
