# Generated by Django 3.2.20 on 2024-05-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_structure', '0002_auto_20240513_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='child',
            field=models.ManyToManyField(blank=True, related_name='child_list', to='organizational_structure.Nodes'),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='child_offsets',
            field=models.ManyToManyField(blank=True, related_name='child_offsets_list', to='organizational_structure.Nodes'),
        ),
    ]
