# Generated by Django 3.2.20 on 2024-06-21 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_database', '0010_alter_userpersonil_bko'),
        ('organizational_structure', '0005_auto_20240521_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes',
            name='jabatan',
        ),
        migrations.RemoveField(
            model_name='nodes',
            name='nama',
        ),
        migrations.AddField(
            model_name='nodes',
            name='personnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel_database.userpersonil'),
        ),
    ]
