# Generated by Django 3.2.20 on 2024-04-17 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=240)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubDit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubSatKer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPersonil',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nomor', models.BigIntegerField(blank=True, null=True)),
                ('nama', models.CharField(max_length=120)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'L'), ('P', 'P')], max_length=12)),
                ('nrp', models.BigIntegerField()),
                ('status', models.CharField(choices=[('Aktif', 'AKTIF'), ('Non Aktif', 'NON_AKTIF'), ('Cuti', 'CUTI'), ('Pensiun', 'PENSIUN')], max_length=20)),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel_database.jabatan')),
                ('pangkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel_database.pangkat')),
                ('subdit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel_database.subdit')),
                ('subsatker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel_database.subsatker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
