# Generated by Django 3.2.20 on 2024-04-17 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonil',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
