# Generated by Django 3.2.20 on 2024-04-05 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_database', '0003_subsatker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPersonil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomor', models.BigIntegerField(blank=True, null=True)),
                ('nama', models.CharField(max_length=120)),
                ('jenis_kelamin', models.CharField(choices=[(1, 'L'), (2, 'P')], max_length=12)),
                ('nrp', models.BigIntegerField()),
                ('jabatan', models.CharField(blank=True, max_length=220, null=True)),
                ('status', models.CharField(choices=[(1, 'AKTIF'), (2, 'NON_AKTIF'), (3, 'CUTI'), (4, 'PENSIUN')], max_length=20)),
                ('pangkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel_database.pangkat')),
                ('posisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel_database.posisi')),
                ('subdit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel_database.subdit')),
                ('subsatker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel_database.subsatker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
