# Generated by Django 3.2.20 on 2024-04-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_database', '0004_posisi_userpersonil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonil',
            name='jabatan',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='userpersonil',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'L'), ('P', 'P')], max_length=12),
        ),
        migrations.AlterField(
            model_name='userpersonil',
            name='status',
            field=models.CharField(choices=[('Aktif', 'AKTIF'), ('Non Aktif', 'NON_AKTIF'), ('Cuti', 'CUTI'), ('Pensiun', 'PENSIUN')], max_length=20),
        ),
    ]
