# Generated by Django 3.2.20 on 2024-04-25 08:07

from django.db import migrations, models
import personnel_database.models.pangkat


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_database', '0004_remove_userpersonil_nomor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pangkat',
            name='tipe',
            field=models.CharField(choices=[('PNS POLRI', 'PNS_POLRI'), ('POLRI', 'POLRI')], default=personnel_database.models.pangkat.Pangkat.Tipe['POLRI'], max_length=120),
        ),
    ]
