# Generated by Django 3.2.20 on 2024-05-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_database', '0005_pangkat_tipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonil',
            name='bko',
            field=models.CharField(choices=[('Gasus masuk', 'GASUS_MASUK'), ('Gasum masuk', 'GASUM_MASUK'), ('Gasus keluar', 'GASUS_KELUAR'), ('Gasum keluar', 'GASUM_KELUAR')], max_length=12),
        ),
    ]
