# Generated by Django 3.2.20 on 2024-05-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_database', '0006_alter_userpersonil_bko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jabatan',
            name='nama',
            field=models.CharField(max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='pangkat',
            name='nama',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='subdit',
            name='nama',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='subsatker',
            name='nama',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
