# Generated by Django 3.2.20 on 2024-05-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_database', '0007_auto_20240507_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonil',
            name='nrp',
            field=models.BigIntegerField(max_length=8),
        ),
    ]
