# Generated by Django 3.2.20 on 2024-06-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_database', '0009_alter_userpersonil_nrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonil',
            name='bko',
            field=models.CharField(choices=[('Gasus masuk', 'GASUS_MASUK'), ('Gasum masuk', 'GASUM_MASUK'), ('Gasus keluar', 'GASUS_KELUAR'), ('Gasum keluar', 'GASUM_KELUAR'), ('-', 'NOT_GASUS')], max_length=12),
        ),
    ]
