# Generated by Django 3.2.20 on 2024-05-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing_status', '0002_auto_20240507_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffingstatus',
            name='nama',
            field=models.CharField(max_length=120),
        ),
    ]
