# Generated by Django 3.2.20 on 2024-05-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing_status', '0003_alter_staffingstatus_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffingstatus',
            name='dsp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='staffingstatus',
            name='rill',
            field=models.IntegerField(default=0),
        ),
    ]
