# Generated by Django 3.2.20 on 2024-04-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='authuser',
            name='username',
            field=models.CharField(default='admin', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
